name: Test on Multiple OS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest] # Operating systems to test
        node-version: [18] #14, 16, 18]                      # Node.js versions to test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate report
        run: |
          mkdir -p test-results
          npm test -- --outputFile=test-results/results.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
          name: test-results
          path: test-results/results.json