name: Test on Multiple OS, node and browsers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  browser-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9]
        browser: [chrome-latest, firefox-latest, safari-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run browser-based tests
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          echo "Browser: ${{ matrix.browser }}"
          npx jest test -- --browser=${{ matrix.browser }}

